apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::880269618315:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-A4S0CX71WJ89
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::880269618315:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-09-12T15:50:21Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1196"
  uid: 191e537a-9fb3-435d-b184-fa484965db17
